# Generated by Django 3.0.7 on 2023-03-05 14:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('diagnostic_type', models.TextField(default='standard', max_length=15)),
                ('started', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ended', models.DateTimeField(blank=True)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), size=45)),
            ],
        ),
    ]
