# Generated by Django 3.0.7 on 2023-03-05 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), null=True, size=45),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
