# Generated by Django 3.0.7 on 2023-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_auto_20230305_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('diagnostic_type', models.TextField(default='standard', max_length=15)),
                ('level_1', models.TextField(default='')),
                ('level_2', models.TextField(default='')),
                ('level_3', models.TextField(default='')),
            ],
        ),
    ]
