# Generated by Django 3.0.7 on 2023-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_recomendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendation',
            name='competence_lvl',
            field=models.IntegerField(default=1),
        ),
    ]
