# Generated by Django 3.0.7 on 2023-02-26 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_activesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activesession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
