# Generated by Django 3.0.7 on 2023-03-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_diagnostic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnostic',
        ),
    ]
