# Generated by Django 3.0.7 on 2023-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_diagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('diagnostic_type', models.TextField(default='standard', max_length=15)),
                ('index', models.IntegerField()),
                ('competence_lvl', models.TextField(blank=True, max_length=15)),
                ('recomendation', models.TextField(default='')),
                ('growpoint', models.TextField(default='standard', max_length=15)),
            ],
        ),
    ]
