# Generated by Django 3.0.7 on 2023-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_recomendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesession',
            old_name='expired',
            new_name='expired_at',
        ),
        migrations.AddField(
            model_name='activesession',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
